layouts_dir: _layouts
includes_dir: _includes

title: BfC
subtitle: xxx | xxx | xxx
name: Bridges for Charity
description: An International non-profit organisation
baseurl:
icon: assets/img/bfe_logo.svg
year: 2021

nav:
  HOME:
  subnav1:
    title: Get Involved
    url:
  subnav2:
    title: What We Do
    url:
  subnav3:
    title: Who We Are
    url:

email:
github:
Home:

social:
  medium:
  twitter:
  facebook:
  instagram:
  linkedin:
  youtube:
  github:
  email:
  website:
